language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1

notifications:
  email: false

before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="MathOptInterface", rev="master"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="SemidefiniteOptInterface", rev="bl/moiv0.9"))'
  
after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SDPA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
