# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libopenblas-dev
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# brew update for "Homebrew must be run under Ruby 2.3! You're running 2.0.0"
# brew cask uninstall oclint for https://github.com/travis-ci/travis-ci/issues/8826
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew cask uninstall oclint; brew install libtool gcc; fi
before_script:
  - julia -e 'Pkg.add("MathOptInterface")'
  - julia -e 'Pkg.checkout("MathOptInterface")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceBridges.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/SemidefiniteOptInterface.jl.git")'
after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SDPA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
