# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libopenblas-dev
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install libtool gcc;
    fi
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaInterop/CxxWrap.jl")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SDPA"); Pkg.test("SDPA"; coverage=true)'
after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SDPA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
