# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
language: julia
os:
  - linux
  - osx
# GCC need to be updated for C++14 to be supported
# https://docs.travis-ci.com/user/languages/cpp/
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
julia:
  - 0.7
  - 1.0
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libopenblas-dev
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# brew update for "Homebrew must be run under Ruby 2.3! You're running 2.0.0"
# brew cask uninstall oclint for https://github.com/travis-ci/travis-ci/issues/8826
before_install:
  - eval "${MATRIX_EVAL}" # see https://docs.travis-ci.com/user/languages/cpp/
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew cask uninstall oclint; brew install libtool gcc; fi
after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SDPA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
